### ISSUE TITLE
Shave my head and call me Cecil

### ISSUE THREAD

**Issue by shenders13** [silverjason/weatherly-ios#1]
for the files

**Comment by shenders13** [comment]
Closing issue due to lack of maintainer communication.

**Comment by shenders13** [comment]
Any updates on this?

**Comment by silverjason** [comment]
Hahahahaha

**Comment by silverjason** [comment]
Hi Sam - we rely on community support for the majority of our upgrades. 
Please create a fork and create a PR to upstream so I can review.

You can see more info here 
https://docs.github.com/en/get-started/quickstart/contributing-to-projects

Cecil
